# Generated by Django 5.2.6 on 2026-03-09 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('request', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], default='credit', max_length=15)),
                ('refrence_type', models.CharField(max_length=50)),
                ('refrence_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WalletTransaction', to='accounts.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_form_fee', models.DecimalField(decimal_places=3, max_digits=8)),
                ('provider_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed'), ('refund', 'refund')], default='pending', max_length=15)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('servicerequest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Payment', to='request.servicerequest')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Payment', to='payment.wallettransaction')),
            ],
        ),
    ]
