# Generated by Django 5.2.6 on 2026-03-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
