# Generated by Django 5.2.6 on 2026-03-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_alter_customerprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
