# Generated by Django 5.2.6 on 2026-03-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_customerprofile_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='cnic_image',
            field=models.ImageField(blank=True, null=True, upload_to='provider_documents/'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='provider_profiles/'),
        ),
    ]
