# Generated by Django 5.2.6 on 2026-03-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
