# Generated by Django 5.2.6 on 2026-03-09 11:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
        ('service', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('adress_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('broadcasted', 'broadcasted'), ('accepted', 'accepted'), ('arrived', 'arrived'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=30)),
                ('price_estamited', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('compeleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServiceRequest', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ServiceRequest', to='provider.providerprofile')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServiceRequest', to='service.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServiceStatusLog', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServiceStatusLog', to='request.servicerequest')),
            ],
        ),
    ]
